services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    env_file:
      - .env.docker
    ports:
      - 80:80
  db:
    container_name: postgres_container
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=quiz
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
volumes:
  postgres:
